apiVersion: v1
kind: Secret
metadata:
  name: config-instance-stats
type: Opaque
data:
  OS_REGION_NAME: RegionOne
  OS_PROJECT_DOMAIN_ID: default
  OS_INTERFACE: public
  OS_AUTH_URL: http://public.cloud.com:80/v3
  OS_USERNAME: account
  OS_PROJECT_ID: your-account-id
  OS_USER_DOMAIN_NAME: Default
  OS_PROJECT_NAME: project-name
  OS_PASSWORD: password
  OS_IDENTITY_API_VERSION: 3
  INFLUX_TOKEN: ""
  INFLUX_SERVER: "http://influxd.server.com:8086/"
  INFLUX_BUCKET: ""
  INFLUX_ORG: ""
  STATS_PORT: 3210
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openstack-instance-stats
spec:
  selector:
    matchLabels:
      app: openstack-instance-stats
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: openstack-instance-stats
    spec:
      containers:
      - name: openstack-instance-stats
        image: cheetahfox/openstack-instance-stats:0.2
        envFrom:
        - secretRef:
          name: config-instance-stats
        ports:
        - containerPort: 3210
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3210
        readinessProbe:
          httpGet:
            path: /readyz
            port: 3210
        resources:
          limits:
            cpu: 10m
            memory: 30Mi
          requests:
            cpu: 10m
            memory: 30Mi
      terminationGracePeriodSeconds: 30 